plugins {
	id 'java'
	id 'application'
}

repositories {
	mavenCentral()
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(project.java_version as int)
	}
}

application {
	mainClass = 'dev.relay.server.Main'
	applicationName = project.mod_id + '-server'
}

dependencies {
	implementation project(':common')

	testImplementation platform("org.junit:junit-bom:${project.junit_version}")
	testImplementation 'org.junit.jupiter:junit-jupiter'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
	testLogging {
		events 'passed', 'skipped', 'failed'
	}
}
